name: kisatsingen

services:
  postgres_db:
    image: postgres:18-alpine
    container_name: kisatsingen_postgres_dev
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1gb
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: kisatsingen_dev_db
    ports:
      - "5432:5432"
    volumes:
      - kisatsingen_pgdata:/var/lib/postgresql
      # Explicit local path for init db users and privileges
      - ./local-db-init:/docker-entrypoint-initdb.d

volumes:
  kisatsingen_pgdata: