// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using kisatsingen.Data;

#nullable disable

namespace kisatsingen.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921105315_AddAssistantsAndKnowledgeFiles")]
    partial class AddAssistantsAndKnowledgeFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("chat_entry_seq");

            modelBuilder.Entity("kisatsingen.Data.Entities.Assistant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "UpdatedAt");

                    b.ToTable("Assistants");
                });

            modelBuilder.Entity("kisatsingen.Data.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssistantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssistantId");

                    b.HasIndex("OwnerId", "UpdatedAt");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("kisatsingen.Data.Entities.ChatEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('chat_entry_seq')");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "Seq");

                    b.ToTable("ChatEvents");
                });

            modelBuilder.Entity("kisatsingen.Data.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentsJson")
                        .HasColumnType("text");

                    b.Property<string>("ContentsSchemaVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("FinishReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("ResponseId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('chat_entry_seq')");

                    b.Property<string>("SystemPromptSnapshot")
                        .HasColumnType("text");

                    b.Property<long?>("TimeToFirstTokenMs")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalTokens")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "Seq");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("kisatsingen.Data.Entities.KnowledgeFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssistantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedTokenCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableOfContents")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssistantId");

                    b.HasIndex("ChatId");

                    b.HasIndex("OwnerId");

                    b.ToTable("KnowledgeFiles", t =>
                        {
                            t.HasCheckConstraint("ck_knowledge_files_single_scope", "num_nonnulls(\"AssistantId\", \"ChatId\") = 1");
                        });
                });

            modelBuilder.Entity("kisatsingen.Data.Entities.KnowledgeFileChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstimatedTokenCount")
                        .HasColumnType("integer");

                    b.Property<string>("Heading")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("KnowledgeFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeFileId", "Sequence")
                        .IsUnique();

                    b.ToTable("KnowledgeFileChunks");
                });

            modelBuilder.Entity("kisatsingen.Data.Entities.Chat", b =>
                {
                    b.HasOne("kisatsingen.Data.Entities.Assistant", "Assistant")
                        .WithMany()
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assistant");
                });

            modelBuilder.Entity("kisatsingen.Data.Entities.ChatEvent", b =>
                {
                    b.HasOne("kisatsingen.Data.Entities.Chat", "Chat")
                        .WithMany("Events")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("kisatsingen.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("kisatsingen.Data.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("kisatsingen.Data.Entities.KnowledgeFile", b =>
                {
                    b.HasOne("kisatsingen.Data.Entities.Assistant", "Assistant")
                        .WithMany("KnowledgeFiles")
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("kisatsingen.Data.Entities.Chat", "Chat")
                        .WithMany("KnowledgeFiles")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Assistant");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("kisatsingen.Data.Entities.KnowledgeFileChunk", b =>
                {
                    b.HasOne("kisatsingen.Data.Entities.KnowledgeFile", "KnowledgeFile")
                        .WithMany("Chunks")
                        .HasForeignKey("KnowledgeFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeFile");
                });

            modelBuilder.Entity("kisatsingen.Data.Entities.Assistant", b =>
                {
                    b.Navigation("KnowledgeFiles");
                });

            modelBuilder.Entity("kisatsingen.Data.Entities.Chat", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("KnowledgeFiles");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("kisatsingen.Data.Entities.KnowledgeFile", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
