<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Version>1.0.0</Version>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <DefaultItemExcludes>$(DefaultItemExcludes);browser-designsystemet\package*;browser-chat-client\package*;package*</DefaultItemExcludes>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
      <PackageReference Include="Microsoft.Extensions.AI" Version="10.9.0" />
      <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.9.0" />
      <PackageReference Include="Microsoft.Identity.Web" Version="4.14.2" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
      <PackageReference Include="Vestfold.Extensions.Logging" Version="3.4.1" />
      <PackageReference Include="Vestfold.Extensions.Metrics" Version="1.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="dev-db\" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        <CopyToPublishDirectory>Never</CopyToPublishDirectory>
      </Content>
      <Content Update="appsettings.Development.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        <CopyToPublishDirectory>Never</CopyToPublishDirectory>
      </Content>
    </ItemGroup>

    <Target Name="BundleDesignsystemet" BeforeTargets="BeforeBuild" Inputs="browser-designsystemet\index.ts;browser-designsystemet\package.json" Outputs="wwwroot\designsystemet\designsystemet.mjs;wwwroot\designsystemet\designsystemet.css">
      <Exec Command="npm install" WorkingDirectory="browser-designsystemet" />
      <Exec Command="npm run build" WorkingDirectory="browser-designsystemet" />
    </Target>

    <Target Name="BundleChatClient" BeforeTargets="BeforeBuild" Inputs="browser-chat-client\src\chat-streaming.ts;browser-chat-client\package.json" Outputs="wwwroot\chat-client\chat-client.mjs;wwwroot\chat-client\chat-client.css">
      <Exec Command="npm install" WorkingDirectory="browser-chat-client" />
      <Exec Command="npm run build" WorkingDirectory="browser-chat-client" />
    </Target>

</Project>
